version: "3"
services:
    database:
        image: postgis/postgis:13-master
        # Required when running on platform other than amd64, like Apple M1/M2:
        # platform: linux/amd64
        volumes:
            - ./directus/data/database:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${POSTGRES_DB}"

    directus:
        image: directus/directus:latest
        ports:
            - 8055:8055
        volumes:
            - ./directus/uploads:/directus/uploads
            # If you want to load extensions from the host
            - ./directus/extensions:/directus/extensions
        depends_on:
            - database
        environment:
            KEY: "${DIRECTUS_KEY}"
            SECRET: "${DIRECTUS_SECRET}"

            DB_CLIENT: "pg"
            DB_HOST: "database"
            DB_PORT: "${POSTGRES_PORT}"
            DB_DATABASE: "${POSTGRES_DB}"
            DB_USER: "${POSTGRES_USER}"
            DB_PASSWORD: "${POSTGRES_PASSWORD}"

            ADMIN_EMAIL: "${DIRECTUS_ADMIN_EMAIL}"
            ADMIN_PASSWORD: "${DIRECTUS_ADMIN_PASS}"

            # Make sure to set this in production
            # (see https://docs.directus.io/self-hosted/config-options#general)
            # PUBLIC_URL: 'https://directus.example.com'

